robot:
  name: "robot_name"
  id: 123
sensors:
  - name: "sensor_1"
    type: "lidar"
  - name: "sensor_2"
    type: "camera"

waypoints:
    - name: "waypoint_1"
      position: [0.0, 0.0, 0.0] # [x, y, z]
      orientation: [0.0, 0.0, 0.0] # [roll, pitch, yaw]
    - name: "waypoint_2"
      position: [1.0, 1.0, 1.0]
      orientation: [0.0, 0.0, 0.0]
    - name: "waypoint_3"
      position: [2.0, 2.0, 2.0]
      orientation: [0.0, 0.0, 0.0]
    - name: "waypoint_4"
      position: [3.0, 3.0, 3.0]
      orientation: [0.0, 0.0, 0.0]
    - name: "waypoint_5"
      position: [4.0, 4.0, 4.0]
      orientation: [0.0, 0.0, 0.0]
    - name: "waypoint_6"
      position: [5.0, 5.0, 5.0]
      orientation: [0.0, 0.0, 0.0]


states:
  - name: "start"
    prerequisite: ["None"]
    postrequisite: ["Nav", "Listen"]
  - name: "Nav"
    prerequisite: ["Start", "Pick", "Look For", "Audio Output", "Count"]
    postrequisite: ["Look For", "Place", "Audio Output"]
  - name: "Look For"
    prerequisite: ["Nav"]
    postrequisite: ["Pick", "Listen", "Place", "Nav"]
  - name: "Pick"
    prerequisite: ["Look For"]
    postrequisite: ["Nav"]
  - name: "Place"
    prerequisite: ["Nav", "Look For"]
    postrequisite: ["End"]
  - name: "Listen"
    prerequisite: ["Start", "Audio Output"]
    postrequisite: ["Look For", "Audio Output"]
  - name: "Audio Output"
    prerequisite: ["Listen", "Nav", "Look For"]
    postrequisite: ["Nav", "End"]
  - name: "Follow"
    prerequisite: ["Audio Output"]
    postrequisite: ["End"]
  - name: "End"
    prerequisite: ["Place", "Follow", "Audio Output"]
    postrequisite: ["None"]

