goals:
  - name: "goal1"
    position:
      x: 0.255
      y: -0.062
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: -1.57
  - name: "workroom"
    position:
      x: 1.929
      y: -0.126
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 1.6
  - name: "storage"
    position:
      x: -0.316
      y: 1.445
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 3.074
  - name: "kitchen"
    position:
      x: 1.70
      y: -1.262
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: -1.599
  # - name: "desk"
  #   position:
  #     x: -4.2
  #     y: -1.468
  #     z: 0.0
  #   orientation:
  #     roll: 0.0
  #     pitch: 0.0
  #     yaw: 2.065
